### ISSUE TITLE
support for OrderedDict in when writing record types

### ISSUE THREAD

**Issue by olibook** [tebeka/fastavro#139]
Currently (as 0.16.6), the writer module fails to serialise OrderedDict instances when mapped to a record in a schema when using cpython interpreters.

   ```
avro.schemaless_writer(buff, self.schema, item)
  File "fastavro/_writer.pyx", line 797, in fastavro._writer.schemaless_writer
  File "fastavro/_writer.pyx", line 559, in fastavro._writer.write_data
  File "fastavro/_writer.pyx", line 478, in fastavro._writer.write_record
  File "fastavro/_writer.pyx", line 491, in fastavro._writer.write_record
  File "fastavro/_writer.pyx", line 559, in fastavro._writer.write_data
  File "fastavro/_writer.pyx", line 435, in fastavro._writer.write_union
  File "fastavro/_writer.pyx", line 475, in fastavro._writer.write_union
  File "fastavro/_writer.pyx", line 559, in fastavro._writer.write_data
TypeError: Argument 'datum' has incorrect type (expected dict, got collections.OrderedDict)
```

The use case for supporting ordereddicts as dicts is as follow: we publish data model changes from our django apps to a kafka broker. We prepare the model with django-rest-framework's serialisers to get a "view" of the model. Django-rest-framework returns ordered dicts.

Ordered dicts can be converted to dicts with the dict() constructor. However supporting nested resources requires converting the complete data-structure before sending it to avro's writer.

A trivial test case demonstrating the issue is available here:

https://github.com/olibook/fastavro/commit/b2e8822d70de56e717560ac739b66e640171ca75

it shows that affected versions are python 2.7, 3,4 3.5, 3.6. Unaffected python versions : pypy and pypy3

**Comment by scottbelden** [comment]
@barrywhart It looks like this is due to the cython files defining functions like `write_*` as `cpdef write_record(bytearray fo, dict datum, dict schema)` and so if `datum` is an `OrderedDict` cython thinks it is a different type. I did a quick search seeing if there was a way to have a more generic `mapping` type in cython they would accept all dict-like objects but couldn't find anything right away. Do you have thoughts on how to allow this?

**Comment by barrywhart** [comment]
Interesting. Cython has built-in handling for a handful of native Python types such as `dict`, `list`, `bytes`, and `bytearray`. By this, I mean you can write Python-like code which uses those types directly. Apparently that built-in support requires you to use the exact type, not a subtype.

My best guess on how to support this would be to use a lower-level C function defined by CPython instead of the built-in support. A couple of possibilities:
* [PyDict_Next](https://github.com/cython/cython/blob/master/Cython/Includes/cpython/dict.pxd#L102)
* [PyIter_Next](https://github.com/cython/cython/blob/master/Cython/Includes/cpython/iterator.pxd#L9)

The latter seems preferable, because it is more generic and might also be able to support other collection types, such as a list of key/value tuples. There is an [existing issue](https://github.com/tebeka/fastavro/issues/76) asking for that. I'm not saying that issue is the same, but they are similar ideas (allowing other types in place of `dict`).

**Comment by barrywhart** [comment]
I'll try and look into this. If it has a significant impact on performance, we might want to consider if it's valuable to support. Note that it is not difficult to write application code to convert nested data before passing to the `fastavro` library. The general structure of the code would be very similar in to the [JSON preparation functions](https://github.com/barrywhart/fastavro/blob/66de78e625c47df8cac5bc09643b497cdce84822/fastavro/__main__.py#L12-L27) I included in a PR earlier today.

**Comment by barrywhart** [comment]
I ran a benchmark with the trivial change of changing `write_record()` and `write_map()` to accept an `object` rather than a `dict`. It looks like this results in about a 10-15% performance hit. This is not huge, but it seems like a fairly high cost to *every* user in order to handle a need like this.

I think the performance hit occurs because when the type is `object`, Cython no longer uses dictionary-specific functions like `__Pyx_PyDict_ContainsTF`to check whether a field is present. I suspect we can get the best of both worlds by using C functions like the ones I mention above. When I have time, I will take a look at using those. In the meantime, I suggest a workaround like the one I suggested above (converting the data before writing).

```
Without changes:

Writing 10000 records to one file...
... 10 runs averaged 0.00915930271149 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0144769668579 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.0550956249237 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0886501789093 seconds

With changes:

Writing 10000 records to one file...
... 10 runs averaged 0.0105923891068 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0151430368423 seconds

Writing 10000 records to one file...
... 10 runs averaged 0.065705037117 seconds
Reading 10000 records from one file...
... 10 runs averaged 0.0902446985245 seconds
```

**Comment by scottbelden** [comment]
If there is a way to add support without the performance hit then that would be great, but if not then I would agree that a 10-15% hit for everyone isn't worth it (especially since the need for `OrderedDict` is going to be much smaller in the future with [normal dicts retaining order](https://twitter.com/raymondh/status/941709626545864704))

**Comment by barrywhart** [comment]
I found a [fix](https://github.com/tebeka/fastavro/pull/141) that still performs well.

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/141
