### ISSUE TITLE
Unpin Cython version now that cython/issues/1894 is resolved

### ISSUE THREAD

**Issue by limx0** [tebeka/fastavro#142]
Now that https://github.com/cython/cython/issues/1894 is resolved, is it possible to upgrade setup.py the required cython version to >=0.27 ?

**Comment by scottbelden** [comment]
@barrywhart Can this be done? Is there something other than this issue that was causing a problem? Should we unpin and see what the CI results are?

**Comment by barrywhart** [comment]
Sure! I was not 100% certain the linked issue was the source of the problem, but it definitely sounded similar. IIRC, the symptom was that newer Cython versions caused test failures with Python 3.4. Other versions were unaffected.

I remember discussing this at one point, because we were wondering if it might make sense to stop supporting Python 3.4. I'd say try unpinning it and see what happens. If needed, we can dig up that old PR or issue with the discussion.

**Comment by scottbelden** [comment]
All the checks passed (https://github.com/tebeka/fastavro/pull/143) so I'm going to merge and release a new version.

**Comment by barrywhart** [comment]
Very nice, thanks!
