### ISSUE TITLE
decoding in last versions

### ISSUE THREAD

**Issue by collazosc** [tebeka/fastavro#168]
I was using fastavro 0.14.10 with confluent-kafka python. I installed another machine for testing and it installed fastavro 0.17.9 (last version) but when I run my python program it happen that numeric and date data (from a jdbc stream) is not decoded . For example for a decimal field it shows 'b'0x14 while the old fastavro shows decimal('640').

Same for date.

Where is the problem?

**Comment by scottbelden** [comment]
I don't quite understand. Do you have a simple script that shows the problem?

**Comment by collazosc** [comment]
Hi thanks for you fast answer. The script goes below.

With the old library (fastavro 0.14.10) i get  (  print(msg.value())) something like this:
("fcrea":datetime(2018,3,05,14,05), "code":decimal(685),"name":"test test")
while using the new fastavro version:
("fcrea":43543534453355,"code":'b'0x23,"name":"test test")
I use to receive this answer using java that's why I switched to python, to avoid the painful decode process.
I am using confluent-kafka last version (zookeeper, kafka server, schema registry) with the connect jdbc option. 
-------------------------------------------------
from confluent_kafka import KafkaError
from confluent_kafka.avro import AvroConsumer
from confluent_kafka.avro.serializer import SerializerError
c = AvroConsumer({'bootstrap.servers':  'localhost:9093,localhost:9092','enable.auto.commit':'false',
                       'default.topic.config': {'auto.offset.reset': 'earliest'},
                      'group.id': 'tigoPROD', 'schema.registry.url': 'http://localhost:8081'})
c.subscribe(['as400-DG_GI22ST'])
running = True
while running:
    try:
        msg = c.poll(10)
        if msg:
            if not msg.error():
                print(msg.value())
            elif msg.error().code() != KafkaError._PARTITION_EOF:
                print(msg.error())
                running = False
    except SerializerError as e:
        print("Message deserialization failed for %s: %s" % (msg, e))
        running = False

c.close()

**Comment by scottbelden** [comment]
It looks like `confluent_kafka` tries to use fastavro and then if an exception occurs it falls back to the regular avro. I don't think the regular avro supports logical types which is probably why you are getting values like `43543534453355` instead of your `datetime` object. Could you do two things?

1) Modify your `confluent_kafka` installation to change this line: https://github.com/confluentinc/confluent-kafka-python/blob/e226538d90c1ec9cab630e273f01b8a3fdde32ca/confluent_kafka/avro/serializer/message_serializer.py#L184. Instead of `pass`, change it to `raise`. Then re-run your code. That should raise the exception if one is happening.

2) Are you able to post the schema and any sample data for the messages you are receiving? If so, could you post those?

**Comment by collazosc** [comment]
Hi, sorry for the delay.

I modified code as per item 1 in you email, and I do not see an exception.

About item 2. As I told you I am using schema-registry from confluent so it
automatically creates a schema for the database stream. An easy experiment
to run is to install the software from confluent.io use its example
configuration with mysql enabled and a simple table with date and int types
and the code I've sent you last time. That's why I could send you a schema.

Regards,

---------------------------------
Carlos Collazos
collazosc@gmail.com
----------------------------------

**Comment by scottbelden** [comment]
Can you double check that if you downgrade fastavro to 0.14.10 on the new machine that you get the correct results? Can you also make sure you don't have `avro` or `avro-python3` installed so that we know those aren't being used?

**Comment by glgnohk** [comment]
I've seen a perhaps related issue, at https://github.com/confluentinc/confluent-kafka-python/issues/346#issuecomment-381102614 . It appears that the latest version of confluent-kafka-python causes an exception in fastavro, and thus falls back on avro, which does not have (most?) logical types.

@scottbelden, I made the change you suggested above and did see an exception.  It's the exception in https://github.com/confluentinc/confluent-kafka-python/issues/346#issuecomment-377077704. 

I'm surprised this problem wouldn't be picked up in unit tests for confluent-kafka-python, since it depends heavily on fastavro, if you use Avro. But perhaps they just don't have a test for this, since a exception in fastavro (silently) fails to avro.

@collazosc, perhaps in Python, just try confluent-kafka==0.11.0.

**Comment by scottbelden** [comment]
@glgnohk Okay, that confirms what I expected. I know that `ImmutableDict` is something used in the `avro-python3` library, but I'm not exactly sure how that is bleeding over. I'm guessing the `schema` being passed to `fastavro` is that `ImmutableDict` type, but I'm not quite sure.

**Comment by c-nichols** [comment]
@scottbelden that is what I observed in my environment, see comment here https://github.com/confluentinc/confluent-kafka-python/issues/346#issuecomment-377077704

**Comment by scottbelden** [comment]
@collazosc @glgnohk @c-nichols Would any of you be able to check out and install the `isinstance_not_type` [branch](https://github.com/tebeka/fastavro/compare/isinstance_not_type) and try to reproduce the error? I don't have Kafka set up and don't have a good way of reproducing, but if one of you already has a way of reproducing easily then I think the changes in that branch might resolve the issue (or perhaps cause a new issue).

**Comment by scottbelden** [comment]
This should be resolved in version 0.19.1
