### ISSUE TITLE
ValidationErrorData None Field

### ISSUE THREAD

**Issue by rhaarm** [tebeka/fastavro#210]
@scottbelden remember when decide to change "self.field" to represent as blank string instead of None, but we didn't consider the fact that self.field is immutable considering it's a nametuple...

I'll do a pull request for this to be fixed.

**Comment by scottbelden** [comment]
Oh, I see. I typically don't use `namedtuple` in the `class` form like that (although I've seen it done that way plenty of times) so I forgot about that. This also reminded me that I should probably [add a coverage report](https://github.com/tebeka/fastavro/issues/211) so that we make sure to test all the conditions.

Thanks!

**Comment by rhaarm** [comment]
I'm simply updating the `__str__` to do this...
```python
        field = self.field
        if field is None:
            field = ''
```

**Comment by scottbelden** [comment]
Makes sense :+1:

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/212
