### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by boompig** [tebeka/fastavro#72]
[Here is the documentation for fastavro](https://fastavro.readthedocs.io/en/latest/). Is there more comprehensive documentation anywhere? Something detailing what each of the methods do, and what methods are available?

**Comment by tebeka** [comment]
Sorry, currently no. fastavro is in bugfix mode currently. Patches are appreciated :)

**Comment by rhaarm** [comment]
@tebeka is this package on life support, still in bugfix mode? I'm slightly worried trying to advertise the usage of Avro at work when both the packages seem to be in such bad shape.

**Comment by tebeka** [comment]
Things are much better now. We have two new maintainers who ate doing awesome work.

**Comment by scottbelden** [comment]
@rhaarm The codebase supports modern Avro features such as logical types and just recently got a pretty nice performance boost by customizing the cython code (rather than relying on just the autogenerated cython). However, as you've pointed out, the documentation has fallen by the waist a bit and needs some love.

**Comment by rhaarm** [comment]
Maybe I could assist with documentation, but would need well
documented/commented methods in the cython. I'll review the code and see
what I can accomplish.
