### ISSUE TITLE
logicalType timestamp-millis gotcha

### ISSUE THREAD

**Issue by dodysw** [tebeka/fastavro#90]
I find it hard to understand why the output of deserializing logicalType timestamp-millis field to datetime object, the microsecond property would contain the millisecond value, thus requiring further division by 1000 to turn it back to correct value -- as the unit test shown:

```
def test_logical_types():
    data1 = {
        'date': datetime.date.today(),
        'timestamp-millis': datetime.datetime.now(),
        'timestamp-micros': datetime.datetime.now(),

    }
    binary = serialize(schema, data1)
    data2 = deserialize(schema, binary)
    assert (data1['date'] == data2['date'])
    assert (data1['timestamp-micros'] == data2['timestamp-micros'])
    assert (int(data1['timestamp-millis'].microsecond / 1000) ==
            int(data2['timestamp-millis'].microsecond))
```

What was the original thought behind this?

**Comment by tebeka** [comment]
@kkirsanov @scottbelden ?

**Comment by scottbelden** [comment]
I've never used this logical type, but I _think_ this is correct and it would look more obvious is the `datatime` object had a `.millisecond` attribute.

For example, when I ran this locally I got these values for data1 and data2:

```python
In [51]: data1['timestamp-millis']
Out[51]: datetime.datetime(2017, 8, 5, 16, 5, 39, 233347)

In [52]: data2['timestamp-millis']
Out[52]: datetime.datetime(2017, 8, 5, 16, 5, 39, 233)
```

data2 has lost some precision, but that's because the avro spec says `The timestamp-millis logical type represents an instant on the global timeline, independent of a particular time zone or calendar, with a precision of one millisecond`.

Like I mentioned before, the `datetime` object only has a `.microsecond` attribute, but that can't be compared because of the precision loss:

```python
In [54]: data1['timestamp-millis'].microsecond
Out[54]: 233347

In [55]: data2['timestamp-millis'].microsecond
Out[55]: 233
```

So it's necessary to divide by `1000` in the test to show that they are equivalent. If we assume for a moment that the `datetime` object had a `.millisecond` attribute, the test could be `data1['timestamp-millis'].millisecond == data2['timestamp-millis'].millisecond` because:

```python
In [X]: data1['timestamp-millis'].millisecond
Out[X]: 233

In [X]: data2['timestamp-millis'].millisecond
Out[X]: 233
```

Perhaps the test could be written so that input to `data1` is in millisecond precision to fix the assert, but I _think_ the implementation is correct.

**Comment by dodysw** [comment]
That sounded like the test is just adjusting to the peculiarity of the deserializer to make it pass? 

I think the deserializer is wrong, it should not put millisecond value inside Python's datetime.microsecond in first place. If date1's  has 233347 microsecond, I would accept 233000 microsecond on date2, but not 233.

**Comment by scottbelden** [comment]
Ah, yes, you are right. It looks like @kkirsanov implemented this so hopefully he can chime in, but feel free to submit a PR or I could attempt to make a fix in the next few days, but I haven't used this functionality so as you can tell, I'm not the most familiar with it.

**Comment by dodysw** [comment]
Acknowledged. Created PR #92 for this.

**Comment by kkirsanov** [comment]
Sorry for the slow response.

@scottbelden is Absolutely right

Avro requires timestamp with millisecond precision but python does not provide any similar type. So i chose datetime with limited accuracy.

**Comment by scottbelden** [comment]
Resolved via https://github.com/tebeka/fastavro/pull/92
